/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.seas.unidad3.ejemplo.fastfoodcompany.principal;

import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas.PanelAltaClientes;
import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas.PanelBajaClientes;
import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas.PanelEditarClientes;
import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas.PanelListaClientes;
import java.util.ArrayList;

/**
 *
 * @author PerlaNegra
 */
public class FastFoodCompanyFrame extends javax.swing.JFrame {

    /**
     * Creates new form FastFoodCompanyFrame
     */
    public FastFoodCompanyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        mnuItemAltaCliente = new javax.swing.JMenuItem();
        mnuItemEditarCliente = new javax.swing.JMenuItem();
        mnuItemBajaCliente = new javax.swing.JMenuItem();
        mnuItemLista = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setPreferredSize(new java.awt.Dimension(600, 600));
        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        menuClientes.setText("Clientes");

        mnuItemAltaCliente.setText("Alta cliente");
        mnuItemAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAltaClienteActionPerformed(evt);
            }
        });
        menuClientes.add(mnuItemAltaCliente);

        mnuItemEditarCliente.setText("Editar cliente");
        mnuItemEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEditarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(mnuItemEditarCliente);

        mnuItemBajaCliente.setText("Baja cliente");
        mnuItemBajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBajaClienteActionPerformed(evt);
            }
        });
        menuClientes.add(mnuItemBajaCliente);

        mnuItemLista.setText("Lista clientes");
        mnuItemLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemListaActionPerformed(evt);
            }
        });
        menuClientes.add(mnuItemLista);

        jMenuBar1.add(menuClientes);

        menuEmpleados.setText("Empleados");
        jMenuBar1.add(menuEmpleados);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAltaClienteActionPerformed
        PanelAltaClientes altaClientes=new PanelAltaClientes(this);
        panelContenedor.removeAll();
        panelContenedor.add(altaClientes,java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mnuItemAltaClienteActionPerformed

    private void mnuItemEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEditarClienteActionPerformed
        PanelEditarClientes editarClientes=new PanelEditarClientes(this);
        panelContenedor.removeAll();
        panelContenedor.add(editarClientes,java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mnuItemEditarClienteActionPerformed

    private void mnuItemBajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBajaClienteActionPerformed
        PanelBajaClientes bajaClientes=new PanelBajaClientes(this);
        panelContenedor.removeAll();
        panelContenedor.add(bajaClientes,java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mnuItemBajaClienteActionPerformed

    private void mnuItemListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemListaActionPerformed
        PanelListaClientes listaClientes=new PanelListaClientes(this);
        panelContenedor.removeAll();
        panelContenedor.add(listaClientes,java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mnuItemListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastFoodCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastFoodCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastFoodCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastFoodCompanyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastFoodCompanyFrame().setVisible(true);
            }
        });
    }
           
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenuItem mnuItemAltaCliente;
    private javax.swing.JMenuItem mnuItemBajaCliente;
    private javax.swing.JMenuItem mnuItemEditarCliente;
    private javax.swing.JMenuItem mnuItemLista;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
