package es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas;

import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.acciones.AccionesListaClientes;
import es.seas.unidad3.ejemplo.fastfoodcompany.principal.FastFoodCompanyFrame;
import javax.swing.ListModel;

/**
 *
 * @author PerlaNegra
 */
public class PanelListaClientes extends javax.swing.JPanel {

    private FastFoodCompanyFrame frame;
    private final AccionesListaClientes acciones;
        
    private ListModel<String> modelList;
    /**
     * Creates new form PanelListaClientes
     * @param frame FastFoodCompanyFrame
     */
    public PanelListaClientes(FastFoodCompanyFrame frame) {
        initComponents();
        this.frame = frame;
        this.acciones=new AccionesListaClientes(this);
        
        this.modelList = acciones.listarClientes();
        lista.setModel(modelList);
    }
       
    public FastFoodCompanyFrame getFrame() {
        return frame;
    }

    public void setFrame(FastFoodCompanyFrame frame) {
        this.frame = frame;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        lista.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTA DE CLIENTES"));
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    // End of variables declaration//GEN-END:variables
}
