package es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas;

import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.acciones.AccionesAltaClientes;
import es.seas.unidad3.ejemplo.fastfoodcompany.principal.FastFoodCompanyFrame;
import javax.swing.JTextField;

/**
 *
 * @author PerlaNegra
 */
public class PanelAltaClientes extends javax.swing.JPanel {

    private FastFoodCompanyFrame frame;
    private final AccionesAltaClientes acciones;

    /**
     * Creates new form PanelAltaClientes
     * @param frame FastFoodCompanyFrame
     */
    public PanelAltaClientes(FastFoodCompanyFrame frame) {
        initComponents();
        this.frame = frame;
        this.acciones=new AccionesAltaClientes(this);
    }

    public FastFoodCompanyFrame getFrame() {
        return frame;
    }

    public void setFrame(FastFoodCompanyFrame frame) {
        this.frame = frame;
    }

    public JTextField getTxtApellido1() {
        return txtApellido1;
    }

    public JTextField getTxtApellido2() {
        return txtApellido2;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setLayout(null);

        lblNombre.setText("Nombre");
        add(lblNombre);
        lblNombre.setBounds(90, 40, 60, 14);

        lblApellido1.setText("Apellido1");
        add(lblApellido1);
        lblApellido1.setBounds(90, 70, 60, 14);

        lblApellido2.setText("Apellido2");
        add(lblApellido2);
        lblApellido2.setBounds(90, 100, 60, 14);
        add(txtNombre);
        txtNombre.setBounds(150, 40, 140, 20);
        add(txtApellido1);
        txtApellido1.setBounds(150, 70, 140, 20);
        add(txtApellido2);
        txtApellido2.setBounds(150, 100, 140, 20);

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(190, 140, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        acciones.guardarCliente();
    }//GEN-LAST:event_btnGuardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
